# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab7ead5312f6cc62caa5e072381c951a9c20230a47b136b6abdbcea998cf2bd65e5147f042977ffbac4cb044c5e43791401eae2918f4eb8fa693e7e1454c2e4

test:
  secret_key_base: 05cf8a17373a2a31baccad7bc16f01ce4f9eb2d9b68faa086b9ae01b91848cb6a84230769c906c334a2b86b9768da0d67afb74b6875be2f29c4480b8786360a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
